### ISSUE TITLE
Error converting value {null} to type 'System.Double'. Path 'coordinates.latitude

### ISSUE THREAD

**Issue by jdoan3** [ranga543/YelpFusionSharp#2]
It seems for every YelpFusion api I use I get a similar issue when I am placing a lattitude/longitude value in the autoComplete/GetBusiness/Search functions of the yelp.Api. I really don't know how to get around this. For a test scenario, I used:

request.Term = "Papa Johns Pizza";
request.Latitude = double.Parse("30.0477325");
request.Longitude = double.Parse("-95.18446720000003");

I even used request.Location = "2855 W Lake Houston Pkwy, Kingwood, TX 77339, USA";

yelpSharperClient.Search(new request);

From here when I run the GetSearch I run into the error converting value {null}. I tried doing some searching on why this was the case but couldn't find anything.

I also did a test case where I ran autoComplete for this, which gave me a business Id.
request.Term = "Domino's Pizza";
request.Latitude = double.Parse("30.0498865");
request.Longitude = double.Parse("-95.18670780000002");

I even used request.Location = "4319 Kingwood Dr, Kingwood, TX 77339, USA";

var autocompleteResponse = yelpSharperClient.Autocomplete(new request);

From the business Id I try to get the business from the GetBusiness call but I run into the same error.

var businessResponse= yelpSharperClient.GetBusiness(new autocompleteResponse.Businesses[0].Id);

**Comment by ranga543** [comment]
[Use this version](https://www.nuget.org/packages/YelpFusion.Client/)
`Install-Package YelpFusion.Client -Version 1.0.2`
I tested with this version and it's returning businesses.
